### ISSUE TITLE
Problems about Chi2 rejection

### ISSUE THREAD

**Issue by HouChentripleg** [aau-cns/mars_lib#5]
Thanks for your work.

**Comment by Chris-Bee** [comment]
Hello @HouChentripleg, the X2 value depends on the residual of the sensor update and its variance. In order to cause a high X2 value, either the variance of the residual is too narrow or the residual is too high.

Is the residual for this particular update as you would expect it?

If this is happening right after starting the filter, then one possible issue could be that the initial states are not initialized correctly, and thus rejected.

**Comment by Chris-Bee** [comment]
That makes sense. If all measurements get rejected, then at some point, there is no reliable measurement/state for the prior state.

The initial core state and initial calibration state covariance need to be set according to your uncertainty of the state values that you use for initialization. Uncertainty of the initial measurement used for initialization or uncertainty of the calibration, e.g., Pose sensor w.r.t. IMU.

* Can you tell me what your residuals look like?
* Can you verify that the [pose model](https://github.com/aau-cns/mars_lib#pose-6-dof) fits your input data?
  * Please be sure that the position or rotation is not the inverse (sensor pose w.r.t. navigation world vs. navigation world w.r.t. sensor frame)
* What do you mean by "add some more distinct random noise to the data to test the Chi2"?

* This can also be a symptom of an overconfident core state. This is likely caused by incorrect IMU noise parameters. You can increase the IMU noise parameters for a 'quick test'  (e.g., n*10)
